include:
  - component: $CI_SERVER_FQDN/library/ci/auto-gitlab@main
    inputs:
      auto-rebase: true
      auto-approve: true

      auto-merge: true
      auto-remove-source-branch: true

      auto-tag: true
      auto-tag-pattern: '/^\d+\.\d+\.\d+$/'
      auto-tag-version-major: 0
      auto-tag-version-minor: 4

      auto-release: true

  - component: $CI_SERVER_FQDN/library/ci/build-ansible-collection@main
    inputs:
      collection-path: "k8s-toolkit"

variables:
  CI_DEBUG_TRACE: "true"

stages:
  - build
  - push
  - auto-merge
  - auto-release