---
#vault:
#  path: ns/resource/secret
#  secrets:
#    - s1
#    - s2
#    - s3
#
#ss:
#  access:
#    - s1
#    - s2
#    - s3
#
#es1:
#  ns: 1
#  secrets:
#    - s1
#    - s2
#
#es2:
#  ns: 2
#  secrets:
#    - s2
#    - s3


# Входные
## Обязательные
- debug: var=ns
- debug: var=resource
- debug: var=secret_name
- debug: var=list #(в листе обязательный key)

## Не обязательные
- debug: var=secret_name
- debug: var=cluster_access
- debug: var=sa
- debug: var=store_name
- debug: var=data

# Промежуточные
- name: Facts.
  ansible.builtin.set_fact:
    s_name: "{% if (secret_name is defined) %}{{ secret_name }}{% else %}{{ resource }}-secrets{% endif %}"
    service_account: "{% if (sa is defined) %}{{ sa }}{% else %}{{ resource }}-sa{% endif %}"
    access: "{% if (cluster_access is defined) %}{{ cluster_access }}{% else %}false{% endif %}"
    ss_type: "{% if (cluster_access is true) %}ClusterSecretStore{% else %}SecretStore{% endif %}"
    ss_name: |
      {% if (store_name is defined) %}
        {{ store_name }}
      {% else %}
        {% if (cluster_access is true) %}
          {{ ns }}-{{ resource }}-css
        {% else %}
          {{ resource }}-ss
        {% endif %}
      {% endif %}
    es_data: "{% if (data is defined) %}{{ data }}{% else %}{% endif %}"

- debug: var=s_name
- debug: var=service_account
- debug: var=access
- debug: var=ss_type
- debug: var=ss_name
- debug: var=es_data

- name: Vault secrets.
  ansible.builtin.set_fact:
    keys: " \"{{ secret_data.key }}\": \"{{ secret_data.value }}\" "
  register: vault_secrets
  when: (list | length  > 0) and secret_data.vault is true
  loop: "{{ list }}"
  loop_control:
    label: "{{ secret_data }}"
    loop_var: secret_data

- debug: var=vault_secrets

- name: External secrets.
  ansible.builtin.set_fact:
    es_secrets: "{{ es_secrets | default([]) + [ new_item ] }}"
  vars:
    new_item:
      secretKey: "{% if (secret_data.secretKey is defined) %}{{ secret_data.secretKey }}{% else %}{{ secret_data.key }}{% endif %}"
      remoteRef:
        key: "{% if (secret_data.path is defined) %}{{ secret_data.path }}{% else %}{{ ns }}/{{ resource }}/{{ s_name }}{% endif %}"
        property: "{{ secret_data.key }}"
        decodingStrategy: None
  loop: "{{ list }}"
  loop_control:
    label: "{{ secret_data }}"
    loop_var: secret_data
  when: (list | length  > 0)


- debug: var=es_secrets


- name: External secrets.
  ansible.builtin.set_fact:
    test:
      apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: "{{ s_name }}-es"
        namespace: "{{ ns }}"
      spec:
        secretStoreRef:
          name: "{{ ss_name | replace('/n','') | trim }}"
          kind: "{{ ss_type  | replace('/n','') | trim }}"
        refreshInterval: "1m"
        target:
          name: "{{ s_name }}"
          creationPolicy: Owner
          deletionPolicy: Delete
          template:
            data: "{{ es_data }}"
            type: Opaque # or TLS...
            metadata:
              annotations: {}
              labels: {}
        data: "{{ es_secrets }}"

- debug: var=test

#- name: Create ConfigMap add-secret-script
#  kubernetes.core.k8s:
#    state: present
#    definition:
#      apiVersion: v1
#      kind: ConfigMap
#      metadata:
#        name: add-secret-script
#        namespace: secrets
#      data:
#        add-secret-script.sh: "{{ lookup('ansible.builtin.file', '/source/playbooks/library/vault/add-secret-script.sh') }}"
#
#- name: Remove Job
#  kubernetes.core.k8s:
#    state: absent
#    wait: true
#    definition:
#      apiVersion: batch/v1
#      kind: Job
#      metadata:
#        name: "init-secrets-{{ ns }}-{{ resource }}-{{ s_name }}"
#        namespace: secrets
#  when: "{{ vault_secrets.results | rejectattr('skipped', 'true') | length  > 0 }}"
#
#- name: Create Job
#  kubernetes.core.k8s:
#    state: present
#    wait: true
#    definition:
#      apiVersion: batch/v1
#      kind: Job
#      metadata:
#        name: "init-secrets-{{ ns }}-{{ resource }}-{{ s_name }}"
#        namespace: secrets
#      spec:
#        backoffLimit: 10
#        ttlSecondsAfterFinished: 10
#        manualSelector: true
#        selector:
#          matchLabels:
#            job: "init-secrets-{{ ns }}-{{ resource }}-{{ s_name }}"
#        template:
#          metadata:
#            labels:
#              job: "init-secrets-{{ ns }}-{{ resource }}-{{ s_name }}"
#          spec:
#            containers:
#              - name: create-secret
#                image: "alpine/curl"
#                command: [ash, -c]
#                args:
#                  - "ls -all /tmp/add-secret-script.sh; /tmp/add-secret-script.sh {{ ns }} {{ resource }} {{ service_account }} {{ s_name }} "
#                env:
#                  - name: LIST
#                    value: "{{ vault_secrets.results | rejectattr('skipped', 'true') | map(attribute='ansible_facts.keys') | join(',') }}"
#                volumeMounts:
#                  - mountPath: "/tmp/certs/"
#                    name: cm-vault-tls
#                    readOnly: true
#                  - mountPath: "/tmp/token"
#                    name: vault
#                    subPath: token
#                    readOnly: true
#                  - mountPath: "/tmp/add-secret-script.sh"
#                    name: add-secret-script
#                    subPath: add-secret-script.sh
#                    readOnly: true
#            restartPolicy: Never
#            volumes:
#              - name: cm-vault-tls
#                secret:
#                  secretName: cm-vault-tls
#              - name: vault
#                secret:
#                  defaultMode: 420
#                  secretName: vault
#                  items:
#                    - key: token
#                      path: token
#              - name: add-secret-script
#                configMap:
#                  defaultMode: 500
#                  name: add-secret-script
#                  items:
#                    - key: add-secret-script.sh
#                      path: add-secret-script.sh
#  when: "{{ vault_secrets.results | rejectattr('skipped', 'true') | length  > 0 }}"
#
#- name: Create "{{ namespace_secret }}" namespace
#  kubernetes.core.k8s:
#    name: "{{ ns }}"
#    api_version: v1
#    kind: Namespace
#    state: present
#
#- name: Create ss
#  kubernetes.core.k8s:
#    state: present
#    wait: true
#    definition:
#      apiVersion: external-secrets.io/v1beta1
#      kind: "{{ ss_type }}"
#      metadata:
#        name: "{{ ss_name | replace('/n','') | trim }}"
#        namespace: "{{ ns }}"
#      spec:
#        retrySettings:
#          retryInterval: "10s"
#        provider:
#          vault:
#            server: "https://vault.secrets.svc:8200"
#            version: "v2"
#            namespace: "{{ ns }}"
#            caProvider:
#              type: "Secret"
#              name: "vault-ca"
#              key: "ca.crt"
#            auth:
#              kubernetes:
#                mountPath: "kubernetes"
#                role: "{{ resource }}"
#                # Optional service account reference
#                serviceAccountRef:
#                  name: "{% if (sa is defined) %}{{ sa }}{% else %}{{ resource }}-sa{% endif %}"
#                  namespace: "{{ ns }}"
#  when: "{{ vault_secrets.results | rejectattr('skipped', 'true') | length  > 0 }}"

#
#- name: Create ExternalSecrets
#  kubernetes.core.k8s:
#    state: present
#    wait: true
#    definition:
#      apiVersion: external-secrets.io/v1beta1
#      kind: ExternalSecret
#      metadata:
#        name: "{{ s_name }}-es"
#        namespace: "{{ ns }}"
#      spec:
#        secretStoreRef:
#          name: "{{ ss_name }}"
#          kind: "{{ ss_type }}"
#        refreshInterval: "1m"
#        target:
#          name: "{{ s_name }}"
#          creationPolicy: Owner
#          deletionPolicy: Delete
#          template:
#            data: "{% if (item.template_data is defined) %}{{ item.template_data }}{% else %}{}{% endif %}"
#            type: Opaque # or TLS...
#            metadata:
#              annotations: { }
#              labels: { }
#        data: "{{ item.data }}"
#  with_items: "{{ secrets }}"




#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
## Удаление секрета
#- name: Удаление ss
#  kubernetes.core.k8s:
#    state: absent
#    wait: true
#    definition:
#      apiVersion: external-secrets.io/v1beta1
#      kind: SecretStore
#      metadata:
#        name: "{{ resource }}-ss"
#        namespace: "{{ namespace_secret }}"
#  when: delete is true and cluster_access is false
#
#- name: Удаление ss
#  kubernetes.core.k8s:
#    state: absent
#    wait: true
#    definition:
#      apiVersion: external-secrets.io/v1beta1
#      kind: ClusterSecretStore
#      metadata:
#        name: "{{ resource }}-css"
#  when: delete is true and cluster_access is true
#
#- name: Ресурсы helm
#  ansible.builtin.set_fact:
#    helm_resource_delete: |
#      curl -k --cacert /tmp/certs/ca.crt \
#      --header "X-Vault-Token: $(cat /tmp/token)" \
#      --request DELETE \
#      https://vault.secrets.svc:8200/v1/{{ namespace_secret }}/data/{{ resource }}/{{ name_secret }};
#  when: delete is true
#
#- name: Job удаления секретов
#  kubernetes.core.k8s:
#    state: absent
#    wait: true
#    definition:
#      apiVersion: batch/v1
#      kind: Job
#      metadata:
#        name: "init-secrets-{{ namespace_secret }}-{{ resource }}-{{ name_secret }}-delete"
#        namespace: secrets
#  when: delete is true
#
#- name: Job удаления секретов
#  kubernetes.core.k8s:
#    state: present
#    wait: true
#    definition:
#      apiVersion: batch/v1
#      kind: Job
#      metadata:
#        name: "init-secrets-{{ namespace_secret }}-{{ resource }}-{{ name_secret }}-delete"
#        namespace: secrets
#      spec:
#        backoffLimit: 5
#        ttlSecondsAfterFinished: 120
#        template:
#          spec:
#            containers:
#              - name: post-start
#                image: "curlimages/curl"
#                command: [sh, -c]
#                args:
#                  - "{{ helm_resource_delete }}"
#                volumeMounts:
#                  - mountPath: "/tmp/certs/"
#                    name: cm-vault-tls
#                    readOnly: true
#                  - mountPath: "/tmp/token"
#                    name: vault
#                    subPath: token
#                    readOnly: true
#            restartPolicy: Never
#            volumes:
#              - name: cm-vault-tls
#                secret:
#                  secretName: cm-vault-tls
#              - name: vault
#                secret:
#                  secretName: vault
#                  items:
#                    - key: token
#                      path: token
#                      mode: 0640
#  when: delete is true
