---

- debug: var=cluster_access
- debug: var=update_secret
- debug: var=delete
- debug: var=name
- debug: var=list
- name: Секреты.
  ansible.builtin.set_fact:
    keys: " \"{{ secret_data.key }}\": \"{{ secret_data.value }}\" "
  register: keys_result
  loop: "{{ list }}"
  loop_control:
    label: "{{ secret_data }}"
    loop_var: secret_data
  when: delete is false

- debug: var=keys_result

- name: Удаление ConfigMap job-add-kv
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: add_vault_secret
        namespace: secrets

- name: ConfigMap job-add-kv
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: add_vault_secret
        namespace: secrets
      data:
        add_vault_secret.sh: "{{ lookup('ansible.builtin.file', '/source/playbooks/library/vault/add_vault_secret.sh') }}"

- name: Удаление Job создание секретов
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "init-secrets-{{ namespace }}-{{ resource }}-{{ name }}"
        namespace: secrets


- name: Job создание секретов
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "init-secrets-{{ namespace }}-{{ resource }}-{{ name }}"
        namespace: secrets
      spec:
        backoffLimit: 1200
        ttlSecondsAfterFinished: 120
        template:
          spec:
            containers:
              - name: post-start
                image: "curlimages/curl"
                command: [sh, -c]
                args:
                  - "/tmp/add_vault_secret.sh {{ namespace }} {{ resource }} {{ resource }}-sa {{ name }} "
                env:
                  - name: LIST
                    value: "{{ keys_result.results | map(attribute='ansible_facts.keys') | join(',') }}"
                volumeMounts:
                  - mountPath: "/tmp/certs/"
                    name: cm-vault-tls
                    readOnly: true
                  - mountPath: "/tmp/token"
                    name: vault
                    subPath: token
                    readOnly: true
                  - mountPath: "/tmp/add_vault_secret.sh"
                    name: add_vault_secret
                    subPath: add_vault_secret.sh
                    readOnly: true
            restartPolicy: Never
            volumes:
              - name: cm-vault-tls
                secret:
                  secretName: cm-vault-tls
              - name: vault
                secret:
                  secretName: vault
                  items:
                    - key: token
                      path: token
                      mode: 0540
              - name: job-add-kv
                configMap:
                  name: add_vault_secret
                  items:
                    - key: add_vault_secret.sh
                      path: add_vault_secret.sh
                      mode: 0740
  when: delete is false and update_secret is true

- name: Create "{{ namespace }}" namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when: delete is false

- name: add label to existing namespace
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ namespace }}"
    definition:
      metadata:
        labels:
          bundle.ca.vault: "true"
  when: delete is false

- name: Создание sa
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ resource }}-sa"
        namespace: "{{ namespace }}"
  when: delete is false

- name: Создание Bundle с сертификатом vault
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: trust.cert-manager.io/v1alpha1
      kind: Bundle
      metadata:
        name: "cm-vault-tls-ca"
      spec:
        sources:
          - useDefaultCAs: false
          - secret:
              name: "cm-vault-tls"
              key: "ca.crt"
        target:
          secret:
            key: "ca.crt"
          additionalFormats:
            jks:
              key: "bundle.jks"
            pkcs12:
              key: "bundle.p12"
          namespaceSelector:
            matchLabels:
              bundle.ca.vault: "true"

- name: Создание ss
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: "{{ resource }}-ss"
        namespace: "{{ namespace }}"
      spec:
        retrySettings:
          retryInterval: "10s"
        provider:
          vault:
            server: "https://vault.secrets.svc:8200"
            version: "v2"
            namespace: "{{ namespace }}"
            caProvider:
              type: "Secret"
              name: "cm-vault-tls-ca"
              key: "ca.crt"
            auth:
              kubernetes:
                mountPath: "kubernetes"
                role: "{{ resource }}"
                # Optional service account reference
                serviceAccountRef:
                  name: "{{ resource }}-sa"
  when: delete is false and cluster_access is false

- name: Создание ss
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        name: "{{ resource }}-css"
      spec:
        retrySettings:
          retryInterval: "10s"
        provider:
          vault:
            server: "https://vault.secrets.svc:8200"
            version: "v2"
            namespace: "{{ namespace }}"
            caProvider:
              type: "Secret"
              name: "cm-vault-tls-ca"
              namespace: "{{ namespace }}"
              key: "ca.crt"
            auth:
              kubernetes:
                mountPath: "kubernetes"
                role: "{{ resource }}"
                # Optional service account reference
                serviceAccountRef:
                  name: "{{ resource }}-sa"
                  namespace: "{{ namespace }}"
  when: delete is false and cluster_access is true

# Удаление секрета
- name: Отключение бандла рассылки ca vault.
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ namespace }}"
    definition:
      metadata:
        labels:
          bundle.secret.vault: ""
  when: delete is true

- name: Удаление ss
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: "{{ resource }}-ss"
        namespace: "{{ namespace }}"
  when: delete is true and cluster_access is false

- name: Удаление ss
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      metadata:
        name: "{{ resource }}-css"
  when: delete is true and cluster_access is true

- name: Удаление sa
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ resource }}-sa"
        namespace: "{{ namespace }}"
  when: delete is true

- name: Ресурсы helm
  ansible.builtin.set_fact:
    helm_resource_delete: |
      curl -k --cacert /tmp/certs/ca.crt \
      --header "X-Vault-Token: $(cat /tmp/token)" \
      --request DELETE \
      https://vault.secrets.svc:8200/v1/{{ namespace }}/data/{{ resource }}/{{ name }};
  when: delete is true

- name: Job удаления секретов
  kubernetes.core.k8s:
    state: absent
    wait: true
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "init-secrets-{{ namespace }}-{{ resource }}-{{ name }}-delete"
        namespace: secrets
  when: delete is true

- name: Job удаления секретов
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "init-secrets-{{ namespace }}-{{ resource }}-{{ name }}-delete"
        namespace: secrets
      spec:
        backoffLimit: 5
        ttlSecondsAfterFinished: 120
        template:
          spec:
            containers:
              - name: post-start
                image: "curlimages/curl"
                command: [sh, -c]
                args:
                  - "{{ helm_resource_delete }}"
                volumeMounts:
                  - mountPath: "/tmp/certs/"
                    name: cm-vault-tls
                    readOnly: true
                  - mountPath: "/tmp/token"
                    name: vault
                    subPath: token
                    readOnly: true
            restartPolicy: Never
            volumes:
              - name: cm-vault-tls
                secret:
                  secretName: cm-vault-tls
              - name: vault
                secret:
                  secretName: vault
                  items:
                    - key: token
                      path: token
                      mode: 0640
  when: delete is true
