namespace: library
name: k8s_toolkit
version: "1.0.0"
readme: README.md
authors:
  - "Your Name firzen475@gmail.com"
description: "Всякая полезная штука."
license:
  - "MIT"
repository: "https://gitlab.fzen.pro/library/ansible.git"

