
- name: Debug secret_entry
  ansible.builtin.debug:
    var: secret_entry

- name: Add secret data item
  ansible.builtin.set_fact:
    compiled_secret_data: "{{ compiled_secret_data + [ {
      'secretKey': (secret_record.extra_parameters | default({})).secretKey | default(secret_record.name),
      'remoteRef': {
        'conversionStrategy': 'Default',
        'decodingStrategy': (secret_record.extra_parameters | default({})).decodingStrategy | default(None),
        'key': secret_entry.key,
        'metadataPolicy': 'None',
        'property': secret_record.name
      }
    } ] }}"
  loop: "{{ secret_entry.value }}"
  loop_control:
    loop_var: "secret_record"


