

- name: Debug external-secret
  debug:
    msg: "{{ _es_state }} {{ _es_namespace }} {{ _es_name }} {{ _es_access_zone }} {{ _ss_name }} {{ _ss_access_zone }} {{ _secret_name }} {{ _secret_type }} {{ _template_data }} {{ _secret_list }}"

- name: "Update external-secret {{ _es_namespace }}/{{ _es_name }} ({{ _es_access_zone }})"
  kubernetes.core.k8s:
    state: "{{ _es_state }}"
    apply: true
    definition:
      apiVersion: external-secrets.io/v1beta1
      kind: "{{ _es_access_zone }}"
      metadata:
        name: "{{ _es_name }}"
        namespace: "{{ _es_namespace }}"
      spec:
        secretStoreRef:
          name: "{{ _ss_name }}"
          kind: "{{ _ss_access_zone }}"
        target:
          name: "{{ _secret_name }}"
          creationPolicy: Owner
          deletionPolicy: Delete
          template:
            data: "{{ _template_data | default(omit,true) }}"
            type: "{{ _secret_type | default('Opaque',true) }}"
        data: "{{ _secret_list }}"