

- name: Debug external-secret
  debug:
    msg: "{{ _es_state }} {{ _es_namespace }} {{ _es_name }} {{ _es_access_zone }} {{ _ss_name }} {{ _ss_access_zone }} {{ _secret_name }} {{ _secret_type }} {{ _template_data }} {{ _secret_list }}"

#- name: "Update external-secret {{ es_namespace }}/{{ es_name }} ({{ es_access_zone }})"
#  kubernetes.core.k8s:
#    state: "{{ es_state }}"
#    apply: true
#    definition:
#      apiVersion: external-secrets.io/v1beta1
#      kind: "{{ es_access_zone }}"
#      metadata:
#        name: "{{ es_name }}"
#        namespace: "{{ es_namespace }}"
#      spec:
#        secretStoreRef:
#          name: "{{ ss_name }}"
#          kind: "{{ ss_access_zone }}"
#        target:
#          name: "{{ secret_name }}"
#          creationPolicy: Owner
#          deletionPolicy: Delete
#          template:
#            data: "{{ template_data | default(omit,true) }}"
#            type: "{{ secret_type | default('Opaque',true) }}"
#        data: "{{ list }}"